import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';

import { routes } from './app.routes';
import { provideIcons } from '@ng-icons/core';
import {
  heroHome,
  heroUsers,
  heroDocumentText,
  heroShieldCheck,
  heroCog6Tooth,
  heroArrowLeftOnRectangle,
  heroChartBar,
  heroExclamationCircle,
  heroCheckCircle,
  heroMagnifyingGlass,
  heroMapPin,
  heroClock,
  heroExclamationTriangle,
  heroDocumentCheck,
  heroSquares2x2,
  heroArrowPath,
  heroArrowDownTray,
  heroEye,
  heroArrowTopRightOnSquare,
  heroBars3,
  heroBell,
  heroAdjustmentsHorizontal,
  heroArrowLeft,
  heroHeart,
  heroShare,
  heroInformationCircle,
  heroChevronDown,
  heroChevronLeft,
  heroSquare3Stack3d,
  heroCalendar,
  heroSparkles,
  heroUser,
  heroEnvelope,
  heroLockClosed,
  heroArrowRight,
  heroPhone,
} from '@ng-icons/heroicons/outline';
import { provideHttpClient } from '@angular/common/http';

export const appConfig: ApplicationConfig = {
  providers: [
    provideHttpClient(),
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    provideIcons({
      heroHome,
      heroUsers,
      heroDocumentText,
      heroShieldCheck,
      heroCog6Tooth,
      heroArrowLeftOnRectangle,
      heroChartBar,
      heroExclamationCircle,
      heroCheckCircle,
      heroMagnifyingGlass,
      heroMapPin,
      heroClock,
      heroExclamationTriangle,
      heroDocumentCheck,
      heroSquares2x2,
      heroArrowPath,
      heroArrowDownTray,
      heroEye,
      heroArrowTopRightOnSquare,
      heroBars3,
      heroBell,
      heroAdjustmentsHorizontal,
      heroArrowLeft,
      heroHeart,
      heroShare,
      heroInformationCircle,
      heroChevronDown,
      heroChevronLeft,
      heroSquare3Stack3d,
      heroCalendar,
      heroSparkles,
      heroUser,
      heroEnvelope,
      heroLockClosed,
      heroArrowRight,
      heroPhone,
    }),
  ],
};
